### PR TITLE
Py3 support and version bump

### PR DESCRIPTION
**Pull request by XayOn**
Fixed py3 support and version bump to fix old version in pypi

### CODE REVIEW

**Comment by XayOn** [comment]
I forgot to run tests on Travis. If it does not pass I'll be able to fix it tomorrow, sorry.

**Comment by XayOn** [comment]
I see, python2 does not have isnumeric. Also some environment thing fails

**Comment by XayOn** [comment]
I see, python2 has not isnumeric. I'll put back isinstance on py2 code tomorrow. Also there seems to be some environment problem

**Comment by sourcepirate** [comment]
@XayOn  Sure.

**Comment by XayOn** [comment]
@sourcepirate 

I fixed environment problems in the tests, extended the classmethods' functionality to support db_path and added TOX so it would run tests on python2.7, python3.4 and python3.5

**Comment by sourcepirate** [comment]
Thanks @XayOn

**Comment by XayOn** [comment]
You're welcome!

**Pull request merged**
